apiVersion: v1
kind: Service
metadata:
  name: go-server
  namespace: go-server
  labels:
    app: go-server
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: go-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: go-server
spec:
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      containers:
      - name: foster
        image: quay.io/lander2k2/go-server:0.1.1
        # exmaple args
        #command: ["./server"]
        #args:
        #- "-cpu-stress"
        #- "-cpu-stressor-duration"
        #- "1000"
        #- "-mem-consume"
        #- "128"
        #- "-backend"
        #- "http://foster-backend"
        #- "-disk-path"
        #- "/"

