apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: go-server
  name: go-server
  namespace: go-server
spec:
  endpoints:
  - honorLabels: true
    port: http
    path: /metrics
  selector:
    matchLabels:
      app: go-server

